{
 "title": "Conso Elec",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Index Heure Creuse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif HC Période",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "currencyEUR",
   "valueName": "diff",
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.00011970" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif en cours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PTEC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif HP Période",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "currencyEUR",
   "valueName": "diff",
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.00015820" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation HP Période",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "kwatt",
   "valueName": "diff",
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation HC Période",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "kwatt",
   "valueName": "diff",
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation instantanée",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PAPP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Heure Pleine",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evolution Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "pleines",
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE  GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "creuses",
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance apparante / Intensité",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Puissance" }
   ],
   "targets": [
    {
     "alias": "puissance_apparente",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PAPP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE  GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    },
    {
     "alias": "intensite",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "IINST",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE  GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures creuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "hc",
     "measurement": "HCHC",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE  GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures pleines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "pl",
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE  GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures pleines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "pl",
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE  GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tz": "UTC"
    }
   ]
  }
 ]
}